// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg8UbKMcRxHnFuWMS91LWV4T_0eKUlU4M',
    appId: '1:337898888952:web:2374c8e948c37cd27ba50d',
    messagingSenderId: '337898888952',
    projectId: 'student-productivity-app-7bb30',
    authDomain: 'student-productivity-app-7bb30.firebaseapp.com',
    storageBucket: 'student-productivity-app-7bb30.firebasestorage.app',
    measurementId: 'G-DKEVCKV7Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0eegfx6wyJQS5eXqRr8WO6vaLHz-u-AM',
    appId: '1:337898888952:android:ad38dc49e770ee717ba50d',
    messagingSenderId: '337898888952',
    projectId: 'student-productivity-app-7bb30',
    storageBucket: 'student-productivity-app-7bb30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8XxdR4ZjfjWODAeXJVRGesHsY5WDmwAc',
    appId: '1:337898888952:ios:0a98128169f8dbd47ba50d',
    messagingSenderId: '337898888952',
    projectId: 'student-productivity-app-7bb30',
    storageBucket: 'student-productivity-app-7bb30.firebasestorage.app',
    iosBundleId: 'com.example.studentProductivityApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8XxdR4ZjfjWODAeXJVRGesHsY5WDmwAc',
    appId: '1:337898888952:ios:0a98128169f8dbd47ba50d',
    messagingSenderId: '337898888952',
    projectId: 'student-productivity-app-7bb30',
    storageBucket: 'student-productivity-app-7bb30.firebasestorage.app',
    iosBundleId: 'com.example.studentProductivityApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg8UbKMcRxHnFuWMS91LWV4T_0eKUlU4M',
    appId: '1:337898888952:web:157a0ec3670c257a7ba50d',
    messagingSenderId: '337898888952',
    projectId: 'student-productivity-app-7bb30',
    authDomain: 'student-productivity-app-7bb30.firebaseapp.com',
    storageBucket: 'student-productivity-app-7bb30.firebasestorage.app',
    measurementId: 'G-17HQ4FP342',
  );

}